baseURL = "http://krupa.net.pl"
languageCode = "en-us"
title = "Landing Page"
theme = "slate"

[ params ]
BackgroundImages = [
  "background.jpg"
]
BackgroundStyle = "#4e4d4b;"
OpenLinksInNewWindow = true
Favicon = "favicon.png"

# list of nav tags
[[ params.nav ]]
name = "favorites"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "productivity"
tag = "productivity"
icon = "space-shuttle"

[[ params.nav ]]
name = "news"
tag = "news"
icon = "info"

[[ params.nav ]]
name = "multimedia"
tag = "multimedia"
icon = "video-camera"
