baseURL = "http://krupa.net.pl"
DefaultContentLanguage = "pl"
languageCode = "pl"
title = "Portal - krupa.net.pl"
theme = "granite"

[ params ]
BackgroundImages = [
  "background.jpg"
]
BackgroundStyle = "#4e4d4b;"
OpenLinksInNewWindow = true
Favicon = "favicon.png"

# list of nav tags
[[ params.nav ]]
name = "ulubione"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "produktywność"
tag = "productivity"
icon = "space-shuttle"

[[ params.nav ]]
name = "wiadomości"
tag = "news"
icon = "info"

[[ params.nav ]]
name = "multimedia"
tag = "multimedia"
icon = "headphones"

[[ params.nav ]]
name = "narzędzia"
tag = "tools"
icon = "wrench"
